[alembic]
# the output encoding used when revision files are written from script.py.mako
output_encoding = utf-8
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current working directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the filename
# (template from file_template)
# unused (0) produces no timestamp pre-processing
# default: 40
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# If set to 'true', among the modified files generated by the `revision` command
# a new file .gitignore is also generated if not exists, and the value of the
# following config key (sqlalchemy.url) is masked in .gitignore.
# the value '1' (true) will enable sqlalchemy.url masking, and the value
# 'filename' will specify the filename for the new .gitignore file.
# When the config key gets the filepath (relative or absolute) to a .gitignore
# file, the given path is taken as is, the filename suffix is not appended to it
# if you skip the '.' before the filename_remove_template value, the revision files
# are not removed, so change this value to 'true' to enable the removal
# sqlalchemy.url = driver://user:pass@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
